"""add test data to database third attampt

Revision ID: 03a950f20691
Revises: e28f4ad054f2
Create Date: 2025-04-21 02:00:13.086421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a950f20691'
down_revision: Union[str, None] = 'e28f4ad054f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # получаем метаданные
    meta = sa.MetaData()

    # получаем объекты таблиц
    user_table = sa.Table('user', meta, autoload_with=op.get_bind())
    account_table = sa.Table('account', meta, autoload_with=op.get_bind())

    # вставляем данные в таблицу user
    op.bulk_insert(user_table,
   [
       {'id': 9, 'email': 'test_user5@mail.ru', 'password': 'testpassword', 'full_name': 'Alex'},
       {'id': 10, 'email': 'admin5@mail.ru', 'password': 'somepassword', 'full_name': 'Peter',
        'is_admin': 1}
   ]
   )

    # получаем id созданного пользователя
    connection = op.get_bind()
    r = connection.execute(user_table.select().where(user_table.c.email == 'test_user5@mail.ru')).first()
    user_id = r.id

    # вставляем данные в таблицу account
    op.bulk_insert(account_table,
   [
       {'balance': 0, 'user_id': user_id},
   ]
   )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
