"""add password is_user is_admin fields to users table

Revision ID: 085332f896ba
Revises: 44981ad39a6a
Create Date: 2025-04-18 00:54:21.697875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085332f896ba'
down_revision: Union[str, None] = '44981ad39a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('is_user', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'is_user')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def data_downgrades():
    """Add any optional data downgrade migrations here!"""

    op.execute("delete from my_table")
