"""add test data to database second attampt

Revision ID: 837c22f2786a
Revises: f7e059014cd6
Create Date: 2025-04-21 01:23:19.258869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837c22f2786a'
down_revision: Union[str, None] = 'f7e059014cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # получаем метаданные
    meta = sa.MetaData()

    # получаем объекты таблиц
    user_table = sa.Table('user', meta, autoload_with=op.get_bind())
    account_table = sa.Table('account', meta, autoload_with=op.get_bind())

    # вставляем данные в таблицу user
    op.bulk_insert(user_table,
   [
       {'id': 3, 'email': 'test_user2@mail.ru', 'password': 'testpassword', 'full_name': 'Alex'},
       {'id': 4, 'email': 'admin2@mail.ru', 'password': 'somepassword', 'full_name': 'Peter'}
   ]
   )

    # получаем id созданного пользователя
    connection = op.get_bind()
    r = connection.execute(user_table.select().where(user_table.c.email == 'test_user2@mail.ru')).first()
    user_id = r.id

    # вставляем данные в таблицу account
    op.bulk_insert(account_table,
   [
       {'balance': 0, 'user_id': user_id},
   ]
   )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
