"""add test data to database

Revision ID: f7e059014cd6
Revises: 085332f896ba
Create Date: 2025-04-21 00:45:36.364390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e059014cd6'
down_revision: Union[str, None] = '085332f896ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # получаем метаданные
    meta = sa.MetaData()

    # получаем объект таблицы user
    user_table = sa.Table('user', meta, autoload_with=op.get_bind())

    # вставляем данные в таблицу user
    op.bulk_insert(user_table,
   [
       {'id': 1, 'email': 'test_user@mail.ru', 'password': 'testpassword', 'full_name': 'Alex'},
       {'id': 2, 'email': 'admin@mail.ru', 'password': 'somepassword', 'full_name': 'Peter'}
   ]
   )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
